name: Visualize Repo

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Repo Visualizer
        uses: githubocto/repo-visualizer@0.9.1
